In [3]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("../data/Agri_yield_prediction.csv")

print("Shape:", df.shape)
df.head()

Shape: (10000, 46)

,Temperature,Humidity,Rainfall,Soil_Type,pH,EC,OC,N,P,K,...,Planting_Date,Harvest_Date,Growth_Stage,Irrigation_Frequency,Fertilizer_Type,Pesticide_Usage,Yield,Region,Season,Year
0,21.236204,52.418449,218.999493,Sandy,6.937571,0.891838,0.267994,98.745262,5.273230,28.110766,...,2020-01-01,2020-04-01,Reproductive,2,Organic,Low,8.613835,South,Kharif,2000
1,38.521429,49.974726,55.353599,Clayey,4.655614,2.060172,0.127311,73.177475,144.197737,210.840395,...,2020-01-02,2020-04-02,Vegetative,7,Chemical,High,2.283444,North,Zaid,2003
2,31.959818,40.569235,103.991908,Loamy,6.949041,2.486504,1.495381,150.178286,82.620907,238.076459,...,2020-01-03,2020-04-03,Reproductive,25,Organic,High,8.707448,North,Zaid,2000
3,27.959755,66.436000,198.984191,Sandy,4.858674,2.117828,0.597238,33.275545,106.558078,144.667266,...,2020-01-04,2020-04-04,Vegetative,2,Mixed,Low,9.750230,North,Rabi,2014
4,14.680559,58.597450,144.626803,Loamy,7.341377,0.930743,1.767589,152.547715,137.326588,142.411240,...,2020-01-05,2020-04-05,Maturity,14,Mixed,Medium,2.518869,East,Rabi,2000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 46 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Temperature             10000 non-null  float64
 1   Humidity                10000 non-null  float64
 2   Rainfall                10000 non-null  float64
 3   Soil_Type               10000 non-null  str
 4   pH                      10000 non-null  float64
 5   EC                      10000 non-null  float64
 6   OC                      10000 non-null  float64
 7   N                       10000 non-null  float64
 8   P                       10000 non-null  float64
 9   K                       10000 non-null  float64
 10  Ca                      10000 non-null  float64
 11  Mg                      10000 non-null  float64
 12  S                       10000 non-null  float64
 13  Zn                      10000 non-null  float64
 14  Fe                      10000 non-null  float64
 15  Cu                      10000 non-null  float64
 16  Mn                      10000 non-null  float64
 17  B                       10000 non-null  float64
 18  Mo                      10000 non-null  float64
 19  CEC                     10000 non-null  float64
 20  Sand                    10000 non-null  float64
 21  Silt                    10000 non-null  float64
 22  Clay                    10000 non-null  float64
 23  Bulk_Density            10000 non-null  float64
 24  Water_Holding_Capacity  10000 non-null  float64
 25  Slope                   10000 non-null  float64
 26  Aspect                  10000 non-null  float64
 27  Elevation               10000 non-null  float64
 28  Solar_Radiation         10000 non-null  float64
 29  Wind_Speed              10000 non-null  float64
 30  NDVI                    10000 non-null  float64
 31  EVI                     10000 non-null  float64
 32  LAI                     10000 non-null  float64
 33  Chlorophyll             10000 non-null  float64
 34  GDD                     10000 non-null  float64
 35  Crop_Type               10000 non-null  str
 36  Planting_Date           10000 non-null  str
 37  Harvest_Date            10000 non-null  str
 38  Growth_Stage            10000 non-null  str
 39  Irrigation_Frequency    10000 non-null  int64
 40  Fertilizer_Type         10000 non-null  str
 41  Pesticide_Usage         10000 non-null  str
 42  Yield                   10000 non-null  float64
 43  Region                  10000 non-null  str
 44  Season                  10000 non-null  str
 45  Year                    10000 non-null  int64
dtypes: float64(35), int64(2), str(9)
memory usage: 3.5 MB

In [5]:
df.describe()

,Temperature,Humidity,Rainfall,pH,EC,OC,N,P,K,Ca,...,Solar_Radiation,Wind_Speed,NDVI,EVI,LAI,Chlorophyll,GDD,Irrigation_Frequency,Yield,Year
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,24.824787,60.271793,150.015118,6.490537,1.299315,1.052179,105.189957,77.882509,128.936654,1021.092552,...,548.883988,9.978476,-0.001732,-0.003975,2.992829,30.053218,1593.572485,14.886900,5.469953,2011.984300
std,8.628904,17.357673,86.032127,1.157898,0.693123,0.547959,54.384247,41.760995,69.795901,562.529135,...,259.531126,5.787656,0.577548,0.576211,1.722940,11.541534,806.061301,8.362039,2.633444,7.199753
min,10.000349,30.009465,0.014437,4.500067,0.100251,0.100016,10.028726,5.018852,10.024220,50.057232,...,100.175526,0.000721,-0.999983,-0.999996,0.000052,10.000893,200.051656,1.000000,1.000537,2000.000000
25%,17.389866,45.236748,76.124373,5.487267,0.696678,0.584613,58.195799,41.460738,67.355874,528.872078,...,323.890172,4.937410,-0.504502,-0.504195,1.502946,19.902505,893.715244,8.000000,3.182187,2006.000000
50%,24.775859,60.353807,150.620428,6.475950,1.307264,1.051160,105.025338,78.813574,129.225613,1027.193414,...,551.442577,9.981912,-0.001227,-0.011656,2.986978,29.918376,1587.633472,15.000000,5.444636,2012.000000
75%,32.200190,75.388753,223.402156,7.498969,1.899912,1.530551,152.900276,113.865999,189.642263,1504.748199,...,775.738626,14.928717,0.495559,0.502059,4.485248,40.089844,2287.804118,22.000000,7.779091,2018.000000
max,39.991530,89.995490,299.970293,8.499889,2.499897,1.999885,199.976269,149.980744,249.998090,1999.953150,...,999.919726,19.997770,0.999854,0.999609,5.999257,49.999784,2999.016275,29.000000,9.999242,2024.000000

In [12]:
df.describe(include='object')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17496\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Soil_Type,Crop_Type,Planting_Date,Harvest_Date,Growth_Stage,Fertilizer_Type,Pesticide_Usage,Region,Season
count,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,4,4,10000,10000,3,3,3,4,3
top,Loamy,Maize,2020-01-01,2020-04-01,Reproductive,Chemical,Low,North,Kharif
freq,2581,2554,1,1,3367,3341,3436,2529,3401

###  check  the  missing  values

In [13]:
missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({"Missing Count": missing, "Missing %": missing_percent})
missing_df[missing_df["Missing Count"] > 0].sort_values("Missing %", ascending=False)

Empty DataFrame
Columns: [Missing Count, Missing %]
Index: []

###  check  the  duplicated values

In [7]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

###  get   the  categorical values

In [14]:
categorical_cols = ["Soil_Type", "Crop_Type", "Growth_Stage", "Fertilizer_Type",
                     "Pesticide_Usage", "Region", "Season"]

for col in categorical_cols:
    print(f"\n{col} — {df[col].nunique()} unique values")
    print(df[col].unique())

Soil_Type — 4 unique values
<StringArray>
['Sandy', 'Clayey', 'Loamy', 'Silty']
Length: 4, dtype: str

Crop_Type — 4 unique values
<StringArray>
['Maize', 'Rice', 'Soybean', 'Wheat']
Length: 4, dtype: str

Growth_Stage — 3 unique values
<StringArray>
['Reproductive', 'Vegetative', 'Maturity']
Length: 3, dtype: str

Fertilizer_Type — 3 unique values
<StringArray>
['Organic', 'Chemical', 'Mixed']
Length: 3, dtype: str

Pesticide_Usage — 3 unique values
<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

Region — 4 unique values
<StringArray>
['South', 'North', 'East', 'West']
Length: 4, dtype: str

Season — 3 unique values
<StringArray>
['Kharif', 'Zaid', 'Rabi']
Length: 3, dtype: str

###  check  the  target  variables  distributions

In [10]:
target_col = "Yield"  # update this once you confirm the exact column name (may include units, e.g. "Yield (hg/ha)")

print(df[target_col].describe())
print("\nSkewness:", df[target_col].skew())

count    10000.000000
mean         5.469953
std          2.633444
min          1.000537
25%          3.182187
50%          5.444636
75%          7.779091
max          9.999242
Name: Yield, dtype: float64

Skewness: 0.010597284022555236

###  sanity check

In [15]:
df["Planting_Date"] = pd.to_datetime(df["Planting_Date"])
df["Harvest_Date"] = pd.to_datetime(df["Harvest_Date"])

df["Growing_Duration_Days"] = (df["Harvest_Date"] - df["Planting_Date"]).dt.days

print(df["Growing_Duration_Days"].describe())

count    10000.0
mean        91.0
std          0.0
min         91.0
25%         91.0
50%         91.0
75%         91.0
max         91.0
Name: Growing_Duration_Days, dtype: float64

###  print  the  summary

In [11]:
summary = {
    "n_rows": df.shape[0],
    "n_columns": df.shape[1],
    "columns": df.columns.tolist(),
    "categorical_columns": categorical_cols,
    "numerical_columns": df.select_dtypes(include=np.number).columns.tolist(),
    "missing_values": missing[missing > 0].to_dict(),
    "duplicate_rows": int(duplicate_count)
}

import json
with open("../reports/data_understanding_summary.json", "w") as f:
    json.dump(summary, f, indent=4)

summary

{'n_rows': 10000,
 'n_columns': 46,
 'columns': ['Temperature',
  'Humidity',
  'Rainfall',
  'Soil_Type',
  'pH',
  'EC',
  'OC',
  'N',
  'P',
  'K',
  'Ca',
  'Mg',
  'S',
  'Zn',
  'Fe',
  'Cu',
  'Mn',
  'B',
  'Mo',
  'CEC',
  'Sand',
  'Silt',
  'Clay',
  'Bulk_Density',
  'Water_Holding_Capacity',
  'Slope',
  'Aspect',
  'Elevation',
  'Solar_Radiation',
  'Wind_Speed',
  'NDVI',
  'EVI',
  'LAI',
  'Chlorophyll',
  'GDD',
  'Crop_Type',
  'Planting_Date',
  'Harvest_Date',
  'Growth_Stage',
  'Irrigation_Frequency',
  'Fertilizer_Type',
  'Pesticide_Usage',
  'Yield',
  'Region',
  'Season',
  'Year'],
 'categorical_columns': ['Soil_Type',
  'Crop_Type',
  'Planting_Date',
  'Harvest_Date',
  'Growth_Stage',
  'Fertilizer_Type',
  'Pesticide_Usage',
  'Region',
  'Season'],
 'numerical_columns': ['Temperature',
  'Humidity',
  'Rainfall',
  'pH',
  'EC',
  'OC',
  'N',
  'P',
  'K',
  'Ca',
  'Mg',
  'S',
  'Zn',
  'Fe',
  'Cu',
  'Mn',
  'B',
  'Mo',
  'CEC',
  'Sand',
  'Silt',
  'Clay',
  'Bulk_Density',
  'Water_Holding_Capacity',
  'Slope',
  'Aspect',
  'Elevation',
  'Solar_Radiation',
  'Wind_Speed',
  'NDVI',
  'EVI',
  'LAI',
  'Chlorophyll',
  'GDD',
  'Irrigation_Frequency',
  'Yield',
  'Year'],
 'missing_values': {},
 'duplicate_rows': 0}